package com.remittancemiddleware.remittancemiddleware.entity.enumdata;

public enum Country {
    SINGAPORE, MALAYSIA, CHINA, INDIA, AFGHANISTAN, ALBANIA, ALGERIA, UNITED_STATES_OF_AMERICA, AMERICAN_SAMOA,
    ANDORRA, ANGOLA, ANGUILLA, ANTARCTICA, ANTIGUA_AND_BARBUDA, ARGENTINA, ARMENIA, ARUBA, AUSTRALIA, AUSTRIA,
    AZERBAIJAN, BRITISH_INDIAN_OCEAN_TERRITORY, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, SAINT_BARTHÉLEMY, LESOTHO,
    BELARUS, BELGIUM, BELIZE, BENIN, BERMUDA, BHUTAN, GUINEA_BISSAU, Bolivia_, BONAIRE, _SINT_EUSTATIUS_AND_SABA,
    BOSNIA_AND_HERZEGOVINA, BOUVET_ISLAND, BRAZIL, Virgin_Islands_, UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND,
    BRUNEI_DARUSSALAM, BULGARIA, BURKINA_FASO, MYANMAR, BURUNDI, CABO_VERDE, CAMBODIA, CAMEROON, CANADA, CAYMAN_ISLANDS,
    CENTRAL_AFRICAN_REPUBLIC, CHAD, JERSEY, GUERNSEY, CHILE, TAIWAN, _PROVINCE_OF_CHINA, CHRISTMAS_ISLAND, Cocos_, COLOMBIA,
    COMOROS, Congo, COOK_ISLANDS, COSTA_RICA, CROATIA, CUBA, CURAÇAO, CYPRUS, CZECH_REPUBLIC, DENMARK, DJIBOUTI,
    DOMINICA, DOMINICAN_REPUBLIC, NETHERLANDS, ECUADOR, EGYPT, UNITED_ARAB_EMIRATES, EQUATORIAL_GUINEA, ERITREA, ESTONIA,
    ETHIOPIA, Falkland_Islands_, FAROE_ISLANDS, FIJI, FINLAND, FRANCE, FRENCH_GUIANA, FRENCH_POLYNESIA,
    FRENCH_SOUTHERN_TERRITORIES, GABON, GAMBIA, GEORGIA, GERMANY, GHANA, GIBRALTAR, GREECE, GREENLAND, GRENADA,
    GUADELOUPE, GUAM, GUATEMALA, GUINEA, GUYANA, HAITI, HEARD_ISLAND_AND_MCDONALD_ISLANDS, HONDURAS, HONG_KONG,
    HUNGARY, KIRIBATI, ICELAND, INDONESIA, IRAN, IRAQ, IRELAND, ISRAEL, ITALY,JAMAICA,JAPAN,JORDAN,KAZAKHSTAN,KENYA,
    SAINT_KITTS_AND_NEVIS,KUWAIT,KYRGYZSTAN,LAO,LATVIA,LEBANON,LIBERIA,LIBYA,LIECHTENSTEIN,LITHUANIA,LUXEMBOURG,MACAO,
    Macedonia_,MAYOTTE,MADAGASCAR,MALAWI,MALDIVES,MALI,MALTA,ISLE_OF_MAN,MARSHALL_ISLANDS,MARTINIQUE,MAURITANIA,MAURITIUS,
    MEXICO,Micronesia_,Moldova_,MONGOLIA,MONTENEGRO,MONTSERRAT,MONACO,MOROCCO,BOTSWANA,MOZAMBIQUE,NAMIBIA,NAURU,NEPAL,
    NEW_CALEDONIA,NEW_ZEALAND,VANUATU,NICARAGUA,NIGERIA,NIGER,NIUE,NORFOLK_ISLAND,Korea_,NORTHERN_MARIANA_ISLANDS,NORWAY,
    OMAN,PAKISTAN,PALAU,PALESTINE,_STATE_OF,PANAMA,PAPUA_NEW_GUINEA,PARAGUAY,PERU,PHILIPPINES,PITCAIRN,POLAND,PORTUGAL,
    PUERTO_RICO,QATAR,ROMANIA,RUSSIAN_FEDERATION,RWANDA,RÉUNION,WESTERN_SAHARA,SAINT_HELENA,_ASCENSION_AND_TRISTAN_DA_CUNHA,
    SAINT_LUCIA,SAINT_VINCENT_AND_THE_GRENADINES,Saint_Martin_,SAINT_PIERRE_AND_MIQUELON,EL_SALVADOR,SAN_MARINO,SAMOA,
    SAUDI_ARABIA,SENEGAL,SERBIA,SEYCHELLES,SIERRA_LEONE,Sint_Maarten_,SLOVAKIA,SLOVENIA,SOLOMON_ISLANDS,SOMALIA,SOUTH_AFRICA
    ,SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,KOREAN,SOUTH_SUDAN,SPAIN,SRI_LANKA,SUDAN,SURINAME,SVALBARD_AND_JAN_MAYEN,
    SWAZILAND,SWEDEN,SWITZERLAND,SYRIAN_ARAB_REPUBLIC,SAO_TOME_AND_PRINCIPE,TAJIKISTAN,TANZANIA,_UNITED_REPUBLIC_OF,THAILAND,
    TIMOR_LESTE,TOGO,TOKELAU,TONGA,TRINIDAD_AND_TOBAGO,TUNISIA,TURKEY,TURKMENISTAN,TURKS_AND_CAICOS_ISLANDS,TUVALU,
    Virgin_Islands,UGANDA,UKRAINE,URUGUAY,UZBEKISTAN,VATICAN_CITY_STATE,Venezuela_,VIETNAM,WALLIS_AND_FUTUNA,YEMEN,ZAMBIA,
    ZIMBABWE,ÅLAND_ISLANDS
}

