package com.remittancemiddleware.remittancemiddleware.entity.enumdata;

public enum RemittancePurpose {
    FAMILY_EXPENSES, CHARITY_DONATION, PAYMENT_FOR_SERVICES, TRAVEL_EXPENSES, PERSONAL_ASSET_ALLOCATION,
    PAYMENT_FOR_GOODS, CAPITAL_TRANSFER, INVESTMENT, EMPLOYEE_PAYROLL, GOODS_TRADE, SERVICES_TRADE, RETURN_OF_EXPORT_TRADE,
    LAND_CONSTRUCTION_MORTGAGE_RELATED_PAYMENTS, EDUCATION, SELF
}
